minimumReleaseAgeExclude:
  - '@interop/bnid@6.0.1'
  - '@interop/data-integrity-core@7.0.0'
  - '@interop/did-io@4.0.4'
  - '@interop/did-method-key@7.3.1'
  - '@interop/did-web-resolver@6.2.1'
  - '@interop/ed25519-verification-key@8.0.0'
  - '@interop/jsonld-signatures@11.7.1'
  - '@interop/security-document-loader@9.2.3'
