minimumReleaseAgeExclude:
  - '@interop/did-method-key@7.3.3'
  - '@interop/did-web-resolver@6.2.3'
  - '@interop/http-client@1.0.4'
  - '@interop/jsonld-signatures@11.8.2'
  - '@interop/jsonld@9.0.3'
  - '@interop/security-document-loader@9.4.1'
