minimumReleaseAgeExclude:
  - '@interop/data-integrity-core@6.1.1'
  - '@interop/jsonld-signatures@11.6.7'
  - '@interop/data-integrity-proof@3.2.1'
  - '@interop/did-io@4.0.1'
  - '@interop/did-method-key@7.1.0'
  - '@interop/did-web-resolver@6.1.0'
  - '@interop/ed25519-signature@7.0.1'
  - '@interop/security-document-loader@9.2.1'
